### ISSUE TITLE
Feature request: add stash urls to edits pages too.

### ISSUE THREAD

**Issue by jessqic** [7dJx1qP/stashdb-userscripts#1]
example urls:
https://stashdb.org/users/notjohndoe1234321/edits
https://stashdb.org/edits

accepted edits have scene, performer, studio links which could be linked to local stash instance.

**Comment by 7dJx1qP** [comment]
Good idea. I created a new version, 0.3.0, that adds it.

**Comment by jessqic** [comment]
thanks!
